name: Deploy

on:
  workflow_dispatch:
    inputs:      
      version:
        required: true
        type: string
        description: 'Version to deploy'   
      environment:
        required: false
        type: string
        description: 'Environment to deploy'
      environment-type:
        required: false
        type: string
        description: 'Environment type to deploy []'

jobs:
    call-reusable-workflow:
        name: Deploy
        uses: santander-group-shared-assets/gln-workflows/.github/workflows/cd.yml@v1
        with:
          version: ${{ inputs.version }}
          technology: 'helm'
          environment: ${{ inputs.environment }}
          environment-type: ${{ inputs.environment-type }}
        secrets: inherit
