name: Quality

on:
  pull_request:
    branches:
      - development
      - develop
      - main
      - master
      - release-v[0-9]+.[0-9]+.[xX]

jobs:
  call-reusable-workflow:
    name: Quality
    uses: santander-group-shared-assets/gln-workflows/.github/workflows/npm-quality-image.yml@v1
    secrets: inherit
