name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  call-reusable-workflow:
    name: Release
    uses: santander-group-shared-assets/gln-workflows/.github/workflows/npm-release-gfw.yml@feature/GLUON-36564
    with:
      technology: 'npm'
    secrets: inherit
