name: Template validations

on:
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    name: Template version validation
    uses: santander-group-shared-assets/gln-workflows/.github/workflows/component-template-validations.yml@v1
    secrets: inherit
