spring.profiles.active: local
---
darwin:
  region: boae
  suffix:
  app-name: process
  logging:
    format: GLUONLOG
    gluon-log:
      company: sny
      componentName: darwintestdemo
      componentId: CHANGEIT_CMPT_ID
      componentType: microservice
      appId: CHANGEIT_APP_ID
    entity: ESP
    paas-app-version: "5.3.0"
    kafka:
      server: ${env.logging-server}
  core:
    exceptions:
      error-format: GLUON
  security:
    connectors:
      pkm-connector:
        pkm-endpoint:
          - ${env.pkm-endpoint}

spring:
  application:
    name: sny-process-darwintestdemo
  session:
    store-type: none
  cache:
    type: CAFFEINE #Activated cache caffeine by default (If you want to change the cache to JBoss DataGrid, check the documentacion in confluence)
    caffeine:
      spec: expireAfterWrite=10m #Specifies that each entry should be automatically removed from the cache once that duration has elapsed after the entry’s creation
  lifecycle.timeout-per-shutdown-phase: 2m

logging.level:
  com.santander.sny.process.snyprocessdarwintestdemo.Application: INFO
  root: WARN

management:
  endpoint.health:
    show-details: ALWAYS

health:
  config:
    enabled: false

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html

server:
  forward-headers-strategy: framework
  shutdown: graceful
